### ISSUE TITLE
Traductor

### ISSUE THREAD

**Issue by devjluna** [iojs/iojs-es#102]
Hola que tal soy developer web, me gustaría poder contribuir traduciendo. Saludos

**Comment by eafelix** [comment]
Hola @devjluna si te interesa colaborar con la traducción de la API, pasate por el issue del GT de traducción, tenes ademas varios grupo de trabajo para poder unirte.

**Comment by stringparser** [comment]
Bienvenido @devjluna! Pasa por #83 donde están los grupos de trabajo y podrías ir viendo donde te interesa contribuir. Estamos repartiendo el trabajo en grupos. Por ejemplo, en este momento tenemos pendientes dos traducciones de posts de medium en #81 y #101. Los archivos originales están aquí https://github.com/iojs/evangelism/tree/master/weekly-updates

**Comment by stringparser** [comment]
Ok, acababa de mirar y no estabas añadido como colaborador. Ahora si lo estas ;), ve a http://github.com/iojs

**Comment by a0viedo** [comment]
@devjluna bievenido! podés presentarte también en https://github.com/iojs/iojs-es/issues/41
