### ISSUE TITLE
Migración a la org iojs-es

### ISSUE THREAD

**Issue by stringparser** [iojs/iojs-es#103]
Muy buenas, como veníamos hablando en #84 vamos a dividir el trabajo en los distintos repos de la organización que @edsadr creó (donde están los forks de los repositorios de iojs). Cuando se resuelvan las PRs que hay abiertas nos vamos moviendo al repositorio correspondiente en la org. iojs-es y dejando allí el trabajo propio de cada grupo. 

Este issue lo abro con la idea de pedir +1 para: 
* Merge del directorio [content](https://github.com/iojs/iojs-es/tree/master/content/es) de aquí con el iojs-es/website/content
* Merge del [publications](https://github.com/iojs/iojs-es/tree/master/publications) con iojs-es/evangelism/weekly-updates

También quiero aprovechar para que discutamos que hacer con este repositorio. Se habló de mantener aquí la documentación común (como el GLOSSARY.md) y otros documentos que no pertenezcan a ninguno de los repositorios forkeados de iojs. 

Ya me contais ;)

**Comment by stringparser** [comment]
Necesito respuesta ;)

**Comment by italoacasas** [comment]
@stringparser creo que necesitamos ver cuantas personas aun sigue interesada en el proyecto, luego hacer un meeting por hangout y decidir estas cosas.. Que crees si hacemos un issue a ver cuantas personas siguen presente...

**Comment by pandres95** [comment]
:+1: @stringparser @italoacasas pues si, crear el issue y mirar esa parte.

**Comment by stringparser** [comment]
@italoacasas yo sigo interesado. Para ver cuanta gente hay haciendo cosas [solo tienes que mirar los commits](https://github.com/iojs/iojs-es/commits/master).

**Comment by italoacasas** [comment]
Hasta ahora veo solo 3 personas, contándome a mi.

**Comment by a0viedo** [comment]
yo sigo interesado también @italoacasas. el tema es cuantas horas le puedo dedicar semanalmente, creo que el número hoy está entre 3 y 4hs.

**Comment by italoacasas** [comment]
Me imagino que todos estamos así, el problema es hemos abandonado el proyecto un poco (incluyéndome a mi). Creo que hay que reestructurar un poco los grupos para ver quien esta y quien no. Porque cosas como los boletines y la web necesitan ser atendidos.

**Comment by SametSisartenep** [comment]
Contad conmigo. :+1:

**Comment by soybackend** [comment]
+1 Yo ando interesado, tuve entrega de proyecto el mes pasado y no estuve activo, pero me encargo de algo a partir de mañana mismo.

**Comment by stringparser** [comment]
@iojs/iojs-es ¿migramos entonces el material a [iojs-es]?

**Comment by stringparser** [comment]
(ping) la semana que viene hago la migración si no tengo feedback

**Comment by ripper2hl** [comment]
+1 sigo interesado en el proyecto, pero me habia unido al equipo de website y no encontre pendientes

**Comment by stringparser** [comment]
@ripper2hl, si que hay pendientes mira aquí: https://github.com/iojs-es/website/pulls

**Comment by stringparser** [comment]
Vale, cuando he hecho las PR esta mañana olvidé actualizar el issue que hay aquí del GT Website.  Acabo de hacerlo en #96 (issue del GT para el website), y así hacer referencia al repositorio iojs-es/website.

**Comment by ripper2hl** [comment]
@stringparser pues a trabajar se ha dicho!! :smile: (normalmente lo hago de 7 pm hasta la madrugada)

**Comment by stringparser** [comment]
@ripper2hl, cuando buenamente puedas ;)

**Comment by edsadr** [comment]
ok @stringparser estoy aqui dime si necesitas mi ayuda con algo de esto +1 a la migración obvio

**Comment by stringparser** [comment]
perfect, pues de aqui hay que quitar el _./content_ porque ya está actualizado en iojs-es/website y mover la branch api de este repositorio a la branch api del [iojs-es/io.js](https://github.com/iojs-es/io.js/tree/api). Lo haré durante la semana, si tienes lugar para hacer alguna de las dos cosas no tengas reparo.

**Comment by stringparser** [comment]
Ah, y las [publications](https://github.com/iojs/iojs-es/tree/master/publications) de aquí a la [iojs-es/evangelism](https://github.com/iojs-es/evangelism)

**Comment by pandres95** [comment]
Pero que yo tenga entendido, al final todo ira finalmente en este repo, ¿o no? En cuyo caso, ¿se ha pensado en cómo ir sincronizando todo?

**Comment by stringparser** [comment]
Se supone que cada grupo de trabajo está encargado de tener cada repositorio de la [iojs-es](https://github.com/iojs-es/) al día con el original de la organización de [iojs](https://github.com/iojs). Para sincronizarlo basta con hacer `git remote update && git pull origin && git push origin` en tu clone local. Está detallado en el [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md). En cualquier caso se podría añadir una sección especificando esto.

**Comment by pandres95** [comment]
Ah, ya veo cómo funciona :D
Bueno, me van contando cómo puedo unirme a la migración de la org :3

**Comment by stringparser** [comment]
@pandres95 tu estas en evangelización. Si quieres, una vez se haga el merge de la PR mueve la carpeta publications a iojs-es/evangelism

**Comment by pandres95** [comment]
:+1:

**Comment by stringparser** [comment]
Hecho :)
