### ISSUE TITLE
Traductor

### ISSUE THREAD

**Issue by ripper2hl** [iojs/iojs-es#109]
Quisiera apoyar con algunas traducciones  :smiley:

**Comment by stringparser** [comment]
¡Bienvenido @ripper2hl!

Te invito a ver el issue de los Grupos de trabajo ---> https://github.com/iojs/iojs-es/issues/83
Luego elige alguno y escribe que quieres participar en el issue correspondiente a ese Grupo:
* [Documentación](https://github.com/iojs/iojs-es/issues/94)
* [Evangelización](https://github.com/iojs/iojs-es/issues/95)
* [Website](https://github.com/iojs/iojs-es/issues/96)
* [Revisión](https://github.com/iojs/iojs-es/issues/97)

Un saludo :)

**Comment by a0viedo** [comment]
buenas @ripper2hl, bienvenido! también podés pasar por https://github.com/iojs/iojs-es/issues/41
