### ISSUE TITLE
Colaborador

### ISSUE THREAD

**Issue by paulomcnally** [iojs/iojs-es#110]
Hola, mi nombre es Paulo McNally.

Soy co-fundador de la Comunidad de Node.js Nicaragua en www.nodenica.com

Estoy aquí para apoyar las traducciones al español de io.js

Soy de Nicaragua y tengo 27 años de edad.

PD: Me interesa también la evangelización.

**Comment by stringparser** [comment]
Muy buenas @paulomcnally, bienvenido :). 

Te añado al equipo. Abajo puedes ver una lista de los grupos en los que nos estamos dividiendo el trabajo (issue original donde estan todos #83)

* [Documentación](https://github.com/iojs/iojs-es/issues/94)
* [Evangelización](https://github.com/iojs/iojs-es/issues/95)
* [Website](https://github.com/iojs/iojs-es/issues/96)
* [Revisión](https://github.com/iojs/iojs-es/issues/97)

Pregunta cualquier duda que tengas por aquí. Estamos en el proceso de normalizarlo todo y poner una documentación para colaborar clara y sencilla. Por el momento la idea elegir grupo(s) de trabajo (máximo 2 para no sobrecargarse) y estar al corriente de lo que allí pase. También [tenemos gitter](https://gitter.im/iojs/iojs-es).

Un saludo :)

**Comment by a0viedo** [comment]
@paulomcnally bienvenido! hay un chapter de nodeschool en nicaragua, cierto? 
también podés presentarte si querés en https://github.com/iojs/iojs-es/issues/41

**Comment by paulomcnally** [comment]
Hola @a0viedo no se de algo de nodeschool en Nicaragua.

Saludos
