### ISSUE TITLE
Traducir weekly updates

### ISSUE THREAD

**Issue by julianduque** [iojs/iojs-es#111]
March 20th - https://github.com/iojs/evangelism/blob/master/weekly-updates/weekly-update.2015-03-20.md
March 13th - https://github.com/iojs/evangelism/blob/master/weekly-updates/weekly-update.2015-03-13.md

**Comment by stringparser** [comment]
Cómo vamos con esto?

**Comment by pandres95** [comment]
Puedo subir un PR con lo que ya he traducido, pues estoy por finalizar el primer documento. Me disculparán la tardanza con eso.

**Comment by a0viedo** [comment]
alguien más está con esto? @pandres95 qué documento estás traduciendo? así no nos pisamos

**Comment by pandres95** [comment]
@a0viedo estoy traduciendo el del 20 de marzo

**Comment by stringparser** [comment]
Avisad cuanto acabéis para actualizar el link del website ;)

**Comment by italoacasas** [comment]
https://github.com/iojs/evangelism/blob/master/weekly-updates/weekly-update.2015-04-10.md

**Comment by stringparser** [comment]
¿Alguna novedad por aquí?

**Comment by stringparser** [comment]
pa-pa-ping! :dancer: @iojs/iojs-es

**Comment by pandres95** [comment]
Ya traduje un artículo, faltan muchos :sweat_smile: El PR está [aquí](https://github.com/iojs/iojs-es/pull/120).

**Comment by stringparser** [comment]
Te hice el merge  @pandres95 y migré los artículos con sus autores a [iojs-es/evangelism](https://github.com/iojs-es/evangelism). Para ver los artículos que quedan por traducir ver la carpeta [iojs-es/evangelism/weekly-updates](https://github.com/iojs-es/evangelism/tree/master/weekly-updates). 

Cierro este
