### ISSUE TITLE
Colaborador

### ISSUE THREAD

**Issue by pandres95** [iojs/iojs-es#112]
Mi nombre es Pablo Andrés Dorado Suárez, vivo en Bogotá, tengo 20 años y estoy ansioso por entrar a participar en el grupo de trabajo de i18n de io.js 
Llevo alrededor de un año trabajando con Node.js, y pues pienso que es hora de retribuir todo el beneficio que he recibido a través de una comunidad activa como es la de io.js
Tengo conocimientos un poco más allá de intermedios en inglés (B2), lo cual será muy util a la hora de colaborar con traducciones.

Pueden encontrar más información sobre mi en http://pandres95.me

**Comment by stringparser** [comment]
Muy buenas Pablo, bienvenido! :)

**Comment by stringparser** [comment]
Ok, te acabo de añadir a la organización. Debes de poder ver la invitación en [aqui](https://github.com/iojs)

Te invito a ver el issue de los Grupos de trabajo ---> https://github.com/iojs/iojs-es/issues/83
Luego elige alguno y escribe que quieres participar en el issue correspondiente a ese Grupo:
* [Documentación](https://github.com/iojs/iojs-es/issues/94)
* [Evangelización](https://github.com/iojs/iojs-es/issues/95)
* [Website](https://github.com/iojs/iojs-es/issues/96)
* [Revisión](https://github.com/iojs/iojs-es/issues/97)

Un saludo :)
