### ISSUE TITLE
Traductor 

### ISSUE THREAD

**Issue by rafaecheve** [iojs/iojs-es#113]
Hola, soy Rafael de Mexico

A la orden para apoyar las traducciones al español de io.js

Interesado también en la evangelización.

Gracias!

**Comment by stringparser** [comment]
Buenas @rafaecheve, perdona por el retraso. Como puedes ver está esto un poco parado por ahora. Voy a cerrar este issue. Si sigues interesado puedes leer el [CONTRIBUTING.md](../tree/master/CONTRIBUTING.md). 

¡Saludos!

**Comment by rafaecheve** [comment]
Listo, Gracias no hay problema!
