### ISSUE TITLE
Medium

### ISSUE THREAD

**Issue by pandres95** [iojs/iojs-es#121]
¿Puedo tener un acceso para publicar el artículo que traduje, y los nuevos que siga traduciendo? :D

**Comment by edsadr** [comment]
@pandres95 dame tu mail te hago llegar esa info

**Comment by stringparser** [comment]
Está en su perfil. @pandres95, te lo envío ahora mismo. Usa la cuenta de twitter para logearte a medium. Es la misma.

**Comment by edsadr** [comment]
:( sorry pero no asumo que ese mail sirva siempre :P

**Comment by stringparser** [comment]
:dancer: ¿y porqué lo iba a dejar en el perfil de github si no sirve?

**Comment by edsadr** [comment]
he visto el caso... ponen el mail para el 'spam' que miran cada 8 dias o cuando necesitan algo urgente y mantienen otro personal que es el que se mantiene limpio ...

**Comment by stringparser** [comment]
Pues si, tiene sentido.

**Comment by pandres95** [comment]
Vale. Mi email es pandres95@gentebool.com

**Comment by stringparser** [comment]
Hahhaah, ves al final tenías razón @edsadr

**Comment by stringparser** [comment]
Te lo he mandado al que tienes puesto en github @pandres95, mira allí

**Comment by pandres95** [comment]
Ohhh, con razón no me llegó. Es que... en este momento tengo vencido ese dominio :cry:

**Comment by stringparser** [comment]
ok, te lo reenvio al otro

**Comment by edsadr** [comment]
:P mas vale preguntar siempre LOL

**Comment by stringparser** [comment]
haah, ya ves

**Comment by stringparser** [comment]
Yeah! Ya lo tiene publicado :) 

https://medium.com/@iojs_es/io-js-semana-del-20-de-marzo-fef40049b7f

**Comment by stringparser** [comment]
Y ha puesto el tuit y todo :clap: 

https://twitter.com/iojs_es/status/598245301703614465

¡Buen curro @pandres95!

**Comment by stringparser** [comment]
Ale, cerramos este ;)
