### ISSUE TITLE
First task - translate io.js Week of February 6th 2015

### ISSUE THREAD

**Issue by edsadr** [iojs/iojs-es#2]
Hello

We should start translating this post:

https://medium.com/node-js-javascript/io-js-week-of-february-6th-2015-e185388549a4

**Comment by mikeal** [comment]
I think someone may have already started this one yesterday, I had tweeted out the draft link on accident :)

**Comment by edsadr** [comment]
nice... do you know who is working on it? would be nice to have her/him here involved :)

**Comment by mikeal** [comment]
I think that maybe it was @julianduque

**Comment by mikeal** [comment]
oh nope, it was @a0viedo and it's right here https://medium.com/@a0viedo/504c96cd520d

**Comment by edsadr** [comment]
ok I will ask him... but he has been away the last 2 days.. maybe is too busy

**Comment by bithavoc** [comment]
we should label this issue with a special label so translators are able to find it quickly, should that label be in english or spanish?

**Comment by stringparser** [comment]
For me is ok either one, whichever you prefer

**Comment by a0viedo** [comment]
Anyone want to add corrections to that translation? If not, should I publish the post? Should we create the drafts on GitHub gists for revision?

**Comment by stringparser** [comment]
I don't have corrections :)

**Comment by sorribas** [comment]
On the item 5 it should be Travis CI instead of Tracis CI (typo I guess).

On the item 12 it should be `compañías` instead of `companias`.

**Comment by sergiolepore** [comment]
A few grammar corrections:

- Replace `fué` with `fue`
- Replace `agrego` with `agregó` in `Se agrego soporte de io.js en Tracis CI.`
- Typo in `Tracis CI.`

**Comment by santigimeno** [comment]
I would propose these changes:

- 1st paragraph: `Todos los viernes publicaremos actualizaciones semanales con las novedades dentro y alrededor de iojs `.
- 2nd paragraph: `Mirando todas las contribuciones de Enero, encontramos que fue el tercer mes más activo en la historia de Node (294 commits) y el mes más activo en casi tres años (308 commits en Febrero del 2012). Con el crecimiento de las contribuciones que estamos viendo hasta ahora, esperamos que Febrero sea aún más activo.`
- Point #2: `s/por Sam Newman toma efecto/por Sam Newman es añadido/publicado`
- Point #4: `s/esfuerzos de debuggear/esfuerzos para depurar`.
- Point #12: `s/tu información/la información`

Just my 2 cents :)

**Comment by a0viedo** [comment]
applied the corrections from @sorribas, @sergiolepore and @santigimeno. Just to know that we're all in the same page, everyone understands `debug` for the word `depurar`?

Shouldn't we create an iojs_es account on Medium?

**Comment by stringparser** [comment]
Yep, I understand `depurar` for `debug`. Maybe we could make a Glossary.md so we can have the same vocabulary across translations. Just related to this point 4. should then be:

  4. Google comparte un parte de su trabajo de tracing en V8 y Chrome mientras se concreta la colaboración alrededor de los esfuerzos de *depurar* io.js.

And 12. has a typo
  12. Primer**a** reunión del Tracing Working Group.

**Comment by stringparser** [comment]
Talking about creating an iojs_es medium account, the blog part is being worked at iojs/website#68 by reference of [iojs/website#136](https://github.com/iojs/website/issues/136#issuecomment-73434899)

**Comment by stringparser** [comment]
Glossary landed in #8
