### ISSUE TITLE
Missing contributors emails

### ISSUE THREAD

**Issue by stringparser** [iojs/iojs-es#26]
There are some mails missing in github accounts so I can't send the passwords of Social Media accounts. Send me an email and I'll send them to you
 
@RamirezAlex 
@dayalav 
@a0viedo 
@raxkin 
@juanda95 
@eafelix

**Comment by a0viedo** [comment]
alejandro.oviedo.g@gmail.com

**Comment by eafelix** [comment]
efelixagustin@gmail.com

**Comment by julianduque** [comment]
julianduquej@gmail.com

**Comment by RamirezAlex** [comment]
alexander.ramirez@gmail.com

**Comment by ipeluffo** [comment]
ipeluffo@gmail.com

**Comment by byoigres** [comment]
byoigres@gmail.com

**Comment by stringparser** [comment]
@iojs/iojs-es a alguno le falta la contraseña de twitter, gmail, etc?

**Comment by julianduque** [comment]
Cómo se está gestionando el tema de contraseñas y eso? Deberiamos tener un file cifrado con nuestras llaves GPG usando keybase.io o si eso ya se discutió me retiro lentamente.. hehehe

Si alguien quiere invitación a keybase creo que tengo un par

**Comment by ipeluffo** [comment]
@julianduque , con gusto aceptaría una invitación para keybase. Gracias de antemano
Me sumo a la consulta de cómo se están manejando las credenciales de las distintas cuentas.

**Comment by julianduque** [comment]
@ipeluffo enviada!

**Comment by stringparser** [comment]
yo también si aún te queda @julianduque :)

**Comment by julianduque** [comment]
@stringparser enviada!

**Comment by edsadr** [comment]
tengo 4 yo también, quien haga falta que cuente :dash:

**Comment by academo** [comment]
Yo?

**Comment by edsadr** [comment]
enviada la primera a @academo

**Comment by rcotrina94** [comment]
Yo también quiero una invitación a Keybase.io! >_<'

PD.: ¿Tengo que dar mi e-mail?

**Comment by stringparser** [comment]
gracias @julianduque :)

**Comment by edsadr** [comment]
@rcotrina94 seria bueno :p es el que tienes en el perfil de github?

**Comment by rcotrina94** [comment]
rcotrina@pytel.pe :)

**Comment by stringparser** [comment]
@julianduque ¿tienes las claves? Creo que no. Voy a enviártelas junto con el resto de gente que aún no las tiene. Volviendo a lo que dijiste de keybase, no se habló aún así que no te retires hahahaha. 

A ver si la semana que viene dejamos todas las tareas administrativas bien atadicas entre el hangout (#64) y demás :)

**Comment by julianduque** [comment]
Hablemos en el Hangout y asi todos tenemos idea de como proceder :)

**Comment by stringparser** [comment]
Cerrando, abierto #100
