### ISSUE TITLE
9-13.02.2015 - Tareas pendientes

### ISSUE THREAD

**Issue by stringparser** [iojs/iojs-es#28]
- [x] Publicar artículos https://github.com/iojs/iojs-es/tree/master/publications
- [x] Hacer PR a iojs/website con el contenido ya traducido para [content/es_ES][x-es_ES]
- [ ] Traducir el material para es_AR y es_CO

Bloqueando: 
 - ~~Twitter account~~

[x-es_ES]: https://github.com/iojs/website/tree/master/content
[x-foundation]: https://github.com/iojs/website/tree/master/content

**Comment by edsadr** [comment]
Listo el PR... mal que bien: https://github.com/iojs/website/pull/192

**Comment by stringparser** [comment]
hahah, bueno lo suyo es que vamos haciendo cosas

**Comment by stringparser** [comment]
@iojs/iojs-es dejamos entonces es solo ¿verdad? (para cerrar este)

**Comment by stringparser** [comment]
#46 parece que hay consenso suficiente respecto a sólo hacer "es"
