### ISSUE TITLE
Colaborador / Traductor

### ISSUE THREAD

**Issue by benoror** [iojs/iojs-es#33]
*es_MX*:
> Hola, soy un desarrollador JavaScript desde México. Aunque he sido entusiasta del código abierto desde hace muchos años, nunca antes había contribuido a un proyecto de gran envergadura.
> Sin embargo creo que **io.js** representa una excelente oportunidad para comenzar a contribuir durante mi tiempo libre **(:**
>
> Saludos!

*en_US*:
> Hello, I'm a JavaScript developer from Mexico. Even though I've been a big fan of open source for many years, I never contributed to a major OSS project before.
> However I think **io.js** is a great chance to actively contribute during my free time **(:**
>
> Regards!

**Comment by stringparser** [comment]
Hey :+1: te añadimos ya verdad?

**Comment by benoror** [comment]
ya estoy en la org  :+1:

**Comment by stringparser** [comment]
ok! cerramos este ;)
