### ISSUE TITLE
Weekly Update Feb 13th

### ISSUE THREAD

**Issue by stringparser** [iojs/iojs-es#35]
Weekly update iojs/website/issues/122

**Comment by academo** [comment]
Added to transifex https://www.transifex.com/projects/p/iojs-es/translate/#es/how-iojs-built-a-146-person-27-language-localization-effort-in-one-day/40622390

**Comment by julianduque** [comment]
I'm on transifex now as `julianduque`, please add me to the team or how does that work? :)

**Comment by stringparser** [comment]
Aren't you here? Let me check... no you are not :dancer:, added :)

**Comment by stringparser** [comment]
Also to transifex

**Comment by julianduque** [comment]
:dancers:

**Comment by stringparser** [comment]
haha

**Comment by rcotrina94** [comment]
¿Por qué en inglés? >_<'

**Comment by sergiolepore** [comment]
Buena pregunta, @rcotrina94 😆

**Comment by stringparser** [comment]
Porque empezamos escribiendo en inglés #1

**Comment by rcotrina94** [comment]
@sergiolepore @stringparser ¿Es obligatorio? Si no para comentar en inglés también jaja :)

**Comment by stringparser** [comment]
Para nada ;) lo que te resulte más comodo :)

Texto traducido por @academo ya aquí.
https://github.com/iojs/iojs-es/blob/master/publications/medium-2015-02-13.md

He estado usado el editor de github directamente en la web y la verdad es que es un gustazo para revisar io corregir :) (io corregir yeahh)

**Comment by julianduque** [comment]
Excelente, una pregunta, cómo se está manejando la publicación de estos textos? osea, tenemos una cuenta medium para iojs-es o cómo funciona? :)

**Comment by edsadr** [comment]
@julianduque  https://medium.com/@iojs_es/ y funciona con el twitter que registraste  :P

**Comment by stringparser** [comment]
:smile: sip! La cuenta creo que está en el readme a ver... sip, ahí está aunque es verdad que las redes sociales no se ven demasiado, las pongo arriba que se vean mejor ;)

**Comment by julianduque** [comment]
Así como cuando uno no lee el README y esas cosas :sweat_smile:

**Comment by stringparser** [comment]
hahahaha

**Comment by stringparser** [comment]
Ok, la traducción está en [publications](https://github.com/iojs/iojs-es/blob/master/publications/medium-2015-02-13-semana-del-13-de-Febrero.md) y en [transifex](https://www.transifex.com/projects/p/iojs-es/translate/#es/2015-02-13-semana-del-13-de-febreromd/). falta revisión. He dejado un issue para esto en #53. 

¿Cierro este ok?

**Comment by alejonext** [comment]
ok
