### ISSUE TITLE
Webs de localización como subdominios

### ISSUE THREAD

**Issue by stringparser** [iojs/iojs-es#36]
Abajo hay una buena idea para usar el mismo dominio que iojs

https://github.com/iojs/website/issues/184

**Comment by rcotrina94** [comment]
El problema de los subdominios es con el SEO :/

**Comment by stringparser** [comment]
¡auch! no lo sabía, aunque tiene sentido

**Comment by ipeluffo** [comment]
Según [este mensaje](https://github.com/iojs/website/issues/188#issuecomment-75189134) la URL para Español es https://iojs.org/es

¿Cerramos este issue?

**Comment by julianduque** [comment]
https://iojs.org/es y listo! +1 por cerrar el issue

**Comment by stringparser** [comment]
:scream: :dancers: :dash: :D
