### ISSUE TITLE
Pull Requests al repositorio oficial iojs/website

### ISSUE THREAD

**Issue by ipeluffo** [iojs/iojs-es#38]
Con @edsadr [nos surgió la duda en Gitter](https://gitter.im/iojs/iojs-es?at=54de14f319f1188668702487) si los PR de la traducción de los archivos del repositorio [iojs/website](https://github.com/iojs/website) (*es6.md, faq.md, index.md, template.json*) deberían hacerse desde un fork propio de cada usuario o crear una organización iojs_es y desde allí hacer los PR.

Hacemos votación y aplicamos lo que prefiera la mayoría.

A favor de PR desde forks propios:
1. 

A favor de PR desde organización iojs-es:
1. @ipeluffo
2. @academo 
3. @sergiolepore 
4. @rcotrina94 
5. @stringparser 
6. @benoror

**Comment by ipeluffo** [comment]
Por si les interesa, traductores al Frances optaron por usar forks propios.
Ver: iojs/website#154

**Comment by academo** [comment]
Yo creo que debemos enviar el PR desde la cuenta de iojs-es, de esa forma es la comunidad entera la que hace la contribución y no una persona especifica, de cualquier forma la comunidad siempre esta abierta a recibir a los nuevos miembros, ademas:

Si lo hacemos desde el fork de cada uno no tendría sentido, porque es como decir que esa persona especifica fue la que hizo la traducción cuando fue toda la comunidad que participa en transifex.

**Comment by ipeluffo** [comment]
¿Existe una cuenta iojs-es?

**Comment by sergiolepore** [comment]
Sería bueno mandarlos desde `iojs-es`. Voto por esa alternativa.

**Comment by rcotrina94** [comment]
Yo recién me integro a la Organización de iojs-es en Github, pero creo que si existe dicha cuenta de la comunidad, lo mejor es que los PR se envíen desde ella.

**Comment by stringparser** [comment]
+1, y por esta misma razón todo se debería hacer desde aquí directamente

**Comment by benoror** [comment]
+1 desde `iojs-es`

**Comment by RamirezAlex** [comment]
¿Aparte del equipo de Francés sabemos de otros equipos como lo están haciendo? a mí la verdad me da igual si es desde la cuenta de la organización o desde el fork propio. Más interesante, me parece es que todos los equipos estén alineados en como son los PR del website, para que sea más fácil tanto para ellos como nosotros. No sé si ya lo hicimos, pero tal vez sería bueno preguntarle a Mikeal que le parece mejor a él y el resto del equipo que integrará los PR.

¿Qué les parece?

**Comment by ipeluffo** [comment]
Estuve buscando un poco y veo los siguientes PRs:
* Portugues: https://github.com/iojs/website/pull/176
* Griego: https://github.com/iojs/website/pull/167
* Alemán: https://github.com/iojs/website/pull/171

Todos son PRs de forks propios de los usuarios de los distintos idiomas.

Incluso, en el PR de Alemán leo el siguiente comentario de mikeal:
> I'm going to merge this. If people have improvements they can send them as another PR the way the chinese people are doing.

**Comment by edsadr** [comment]
Por ahora va ganando la opción de la cuenta general... me parece mas bien asi, lo que podemos hacer es referenciar en el PR el crédito de cada traducción.. pero me parece mas unificado así

**Comment by stringparser** [comment]
Este problema va a surgir siempre ya que hay que sacar los archivos primero de transifex porque al final hay que pasarlos a un repositorio de github. 

Propongo lo siguiente: que cada uno haga todo lo que pueda y luego lo añada a este repositorio, se comenta, se corrige, se hace todo lo necesario y se hace la PR cuando esté listo.

**Comment by byoigres** [comment]
Me parece bien lo que @stringparser dice, hay que revisar los PR y si es necesario hacer correcciones se hacen hasta que quede listo.

**Comment by stringparser** [comment]
Y aún así quedan fallos #47

**Comment by edsadr** [comment]
bueno, estamos aprendiendo a trabajar juntos, vamos puliendo el proceso, yo se que @stringparser quiere que cada uno tenga el fork personal, pero el problema esta en corregir todos juntos el PR a un repo personal...  opino que debemos debatir como hacerlo y sobre el uso de transifex... si hay rollo con el pues también lo debatimos... que piensan?

**Comment by stringparser** [comment]
@edsadr toda la razón y +1 a usar la org para tener el material último y corregido. Tengo que buscar una manera simple de tener los dos repos sincronizados

**Comment by ipeluffo** [comment]
Buenas, disculpen pero estuve ausente los últimos días.
Creo que estaría bueno aclarar un poco el workflow de trabajo porque se sigue sumando gente y parece que cada vez es más difícil explicar cómo colaborar.

En Gitter vi un [mensaje](https://gitter.im/iojs/iojs-es?at=54e260c4355bbcc86103e101) de @stringparser que resume de manera concisa el problema:
> pero ahora mismo tenemos 3 lugares donde mirar
el iojs/iojs-es
transifex
y la org iojs-es
3 lugares que sincronizar
si solo tenemos uno y cada uno contribuye lo que puede cuando puede es más simple
porque depende de la semana cada uno tendrá mas o menos tiempo

Propongo lo siguiente: 
1. armemos los pasos que hoy se llevan a cabo desde que se colabora hasta que se publica el contenido en el repositorio oficial de io.js porque el creo que no esta del todo claro cómo se lleva a cabo todo el proceso
2. veamos los puntos débiles o incorrectos
3. acordemos y simplifiquemos el proceso

Primer borrador del proceso:
1. ¿ @stringparser ? copia el nuevo contenido a traducir en [content/es_ES](https://github.com/iojs/iojs-es/tree/master/content/es_ES) o [publications](https://github.com/iojs/iojs-es/tree/master/publications)
2. ¿? copia el nuevo contenido a traducir en el [proyecto en Transifex](https://www.transifex.com/projects/p/iojs-es/)
3. Colaboradores aportan en Transifex
¿
4. Se copia el contenido de Transifex en el [repositorio iojs-es](https://github.com/iojs/iojs-es)
5. Se hacen aportes comentando los cambios en Github
6. Se copian los cambios en el fork hecho en la organización iojs-es
7. Se hace PR al repo oficial
?

**Comment by parroit** [comment]
Hi iojs-es, we are discussing the same question [here](https://github.com/iojs/iojs-it/issues/6).
Would you mind to publish your process in english, just to cooperate and find a best strategy together?

I just tried following process:

1) I create a [website-pr branch on our repo](https://github.com/iojs/iojs-it/tree/website-pr)
2) I completely removed original content from this branch, and pulled all content from [website repo](https://github.com/iojs/website)
3) We'll push all changes to content/it folder to this branch
4) When we'll be ready, one of us will fork [website repo](https://github.com/iojs/website), merge our 
website-pr branch on it, and then publish a PR

What do you think about this steps?

**Comment by stringparser** [comment]
Si, tenemos que quedar en hacer algo simple, que funcione y quizás que no imponga un método particular de trabajo para cada uno (porque esto al final es tiempo libre de cada uno y si muchas veces acaba uno cansado de hacer lo que le manden en el trabajo... para venir a echar un buen rato y encontrase otra lista de cosas que hacer que otra persona ha puesto mejor... que no :D). 

Algo simple que no nos haga estar calentándonos la cabeza y deje la libertad a cada uno a hacerlo como le plazca. En gitter hemos estado hablando de hacer un hangout pronto y supongo que sería el momento idóneo de hablar de esto cuando quedemos. Dejarlo aquí escrito lo que en el hangout se habló para la gente que ese día no pueda esté al tanto, se vote y listo. 

Yo propondría algo que no dependa de la persona y que cualquiera que esté ya (o lo esté en un futuro) pueda hacerse cargo cuando tenga tiempo libre y le apetezca.

Respecto a los pasos, dependerá de cada uno o como finalmente se encuentra con el material. Yo si quereis me encargo de buscar el material nuevo, ponerlo en el repositorio (artículos, etc.) y en caso de que ese material sea texto, también lo pasaría a transifex. Porque aunque yo sigo pensando lo que dejas arriba, que menos es más, quizás me equivoque y simplemente eso: cada uno debe de poder trabajar a su gusto sin dirección de nadie.

Me estoy extendiendo al final :D, pero bueeeno ya que estamos let's :dancers:.

Por lo que vengo aquí comentando se podría poner una lista de cosas que hay que hacer si o si, indiferentemente de la forma en la que finalmente el contenido acabe listo para PR al repo correspondiente, como: 
 1. Tareas administrativas (copiar archivos, buscar en el repositorio el material nuevo)
 2. Búsqueda de tareas en este repo (revisión, correctión, etc.)
 3. Cómo hacer la PR con el material una vez revisado
 4. Que los issues y PRs de este repo siempre estén clasificados para poder encontrarlos

**Comment by stringparser** [comment]
Ouch @parroit, sorry for that :)

We are still discussing it but, basically, from my point of view we only need to make sure that the usual administrative tasks are covered and visible for all, so when whoever has time they can be handled accordingly.

**Comment by stringparser** [comment]
I like what you are doing @parroit

**Comment by parroit** [comment]
Thank you @stringparser, and no worry on language: we're speaking italian in our repo, and I undertand a little of es :-)
I'm more concerned on your point 3), how to publish PR in a easy way. I think the steps I've tried so far made it simple enough, but I'm seeking for some advice from other groups too...

**Comment by stringparser** [comment]
Great, anyhow I'm just one of @iojs/iojs-es and I think others might also have good ways to handle this. 

Respect to 3): yes thats the one that is the pain point for me. But making a new branch is simple enough for anyone (already contributor or not) to put some work together. I've also noticed you have that branch as default. What I would like to have is like a partial history of the iojs/website in this repo regarding only for our changes, if that could be done somehow... it would be awesome.

**Comment by parroit** [comment]
I don't know if it's possible... I'm reading [Git-Branching-Rebasing](http://git-scm.com/book/it/v2/Git-Branching-Rebasing) now. 
If I correctly understood rebase command, we could keep our branch only modified by our community, and then apply our commits on top of iojs website repo before each PR.
In this way, our branch history will show only our changes (except for the ones made before the branch creation) before we don't need to sync it with main repo.

**Comment by stringparser** [comment]
Yes, that would also work in fact :)

Or even plain [git checkout](http://git-scm.com/docs/git-checkout) using branch:path

**Comment by stringparser** [comment]
See here [Nicolas Gallagher post](http://nicolasgallagher.com/git-checkout-specific-files-from-another-branch/)

**Comment by parroit** [comment]
Nice, I will read it. It appear to be the right path, thank you

**Comment by stringparser** [comment]
Welcome, I just remembered from what you pointed out for the [Git-Branching-Rebasing](http://git-scm.com/book/it/v2/Git-Branching-Rebasing) page

**Comment by stringparser** [comment]
I will try to do it directly with the iojs/website as an upstream, if that works... we have gold here :D

**Comment by stringparser** [comment]
Hahah, it f*cking works :), try this in your local repository

```
git remote add upstream-website https://github.com/iojs/website
git remote update
git checkout upstream-website/master content/es_ES
```

**Comment by stringparser** [comment]
Another interesting approach is shown here:
https://github.com/iojs/website/issues/136#issuecomment-76494131

**Comment by stringparser** [comment]
Closing, since all the work will be split in Working Groups, and each WG has a repo that is a fork of iojs's to make the PRs.
