### ISSUE TITLE
Traductor

### ISSUE THREAD

**Issue by vrunoa** [iojs/iojs-es#43]
Hola, ofrezco mi ayuda si necesitan traducir algunos documentos.

**Comment by stringparser** [comment]
Buenas @vrunoa, añadido! :) Pues la versión es_AR y es_CO aún no están así que de perlas.

**Comment by stringparser** [comment]
Entre hoy y mañana lo ponemos aquí y así se puede empezar

**Comment by vrunoa** [comment]
Dale @stringparser , espero los documentos. Saludos.

**Comment by stringparser** [comment]
Ahora mismo seguimos con [transifex](https://www.transifex.com/projects/p/iojs-es), así que te voy añadir allí también

**Comment by vrunoa** [comment]
Buenisimo, ya estoy.

**Comment by rcotrina94** [comment]
@stringparser  ¿Hay es_PE? :)
