### ISSUE TITLE
Links para colaborar

### ISSUE THREAD

**Issue by rcotrina94** [iojs/iojs-es#45]
Se pueden poner parámetros para los issue de Colaborador y Traductor:
- Colaborador : https://github.com/iojs/iojs-es/issues/new?title=Colaborador
- Traductor : https://github.com/iojs/iojs-es/issues/new?title=Traductor

No es necesario ni muy útil, pero es algo que se puede hacer.
También funciona con el parámetro `body`.

https://github.com/iojs/iojs-es/issues/new?title=Colaborador&body=Me%20gustar%C3%ADa%20colaborar,%20tengo%20conocimientos%20de%20A,%20B%20y%20C

Quizás sirve más para poner un modelo de cómo debe ser la petición para unirse a la comunidad, o algún requerimiento o que se presente desde ya.
Saludos!

**Comment by stringparser** [comment]
¡Buena idea! Ponlo en el readme ;)

**Comment by rcotrina94** [comment]
¡A la orden!

**Update:** Ya lo hice, pero sólo con el parámetro `title`, ¿Qué hay de `body`? :)

**Comment by stringparser** [comment]
Lo que quieras tío ;), y tomate la libertad de hacer cosas. Por mi parte siempre que haya un issue acompañando para saber qué se ha hecho libre albedrío :dancers:

**Comment by ipeluffo** [comment]
Este issue podríamos cerrarlo. Que el *body* lo puede completar el usuario a gusto con lo que prefiera :)
