### ISSUE TITLE
i18n language code

### ISSUE THREAD

**Issue by rcotrina94** [iojs/iojs-es#46]
En [Gitter](https://gitter.im/iojs/iojs-es?at=54e0b2c81098fd39548a5fc4) se estaba discutiendo acerca de cómo debía ser la localización al español/castellano, es decir, si debía subdividirse en es_ES, es_CO, es_AR, etc. o no. Entonces surgió la idea de seguir el `ISO 639-1` y establecer una única localización que sería `es`, neutral y con tecnicismos (usar palabras técnicas en inglés). Y estoy aquí para proponer una votación:

# `es` 
**Votos: 11**

- @rcotrina94
- @RamirezAlex 
- @edsadr
- @julianduque
- @ipeluffo
- @academo 
- @007lva
- @byoigres 
- @stringparser
- @vrunoa 
- @sergiolepore 

# `es_ES`, `es_AR`, `es_CO`, etc...
**Votos: 0**

-

**Comment by RamirezAlex** [comment]
+1 para solo es.

**Comment by ipeluffo** [comment]
Mi voto es para "solo es".

Sin embargo me queda la duda si existe alguna diferencia sustancial entre las diferentes localizaciones que haga que el texto no sea entienda para alguna de ellas.

**Comment by RamirezAlex** [comment]
@ipeluffo Yo no creo que exista alguna tal que el texto no se entienda. Igual, antes de dejar la traducción final, pues todos la hemos revisado y afortunadamente tenemos personas de diferentes países colaborando. Así que dado el caso de que alguno note que alguna frase no se entiende en su región, lo hace saber y entre todos buscamos algo más neutral. Si hay algo en lo que es rico nuestro idioma es en sinónimos, entonces seguro encontraremos palabras que se entiendan para todos.

**Comment by academo** [comment]
+1 por mantener un solo español `es`, así mas personas colaboran al mismo tiempo, no creo que existan términos que deban traducirse a una región especifica puesto que en su mayoría son textos técnicos.

**Comment by 007lva** [comment]
+1 solo es, creo que las pequeñas diferencias solo salen a relucir al hablar y casi nada al escribir.

**Comment by byoigres** [comment]
Solo "es"

**Comment by stringparser** [comment]
+1 para solo "es" neutro

**Comment by vrunoa** [comment]
Yo optaría por la opción de solo "es".

**Comment by sergiolepore** [comment]
Disculpen la demora, voto para `es` :smile:

**Comment by rcotrina94** [comment]
Los que votan por favor incluyan su nombre en el issue :/ jaja

**Comment by stringparser** [comment]
Hecho para todos los que faltaban, tampoco era tanto eh?

**Comment by academo** [comment]
Cerramos esto quedando decidido usar solo `es`?

**Comment by julianduque** [comment]
Si, solo `es` por unanimidad, así que podemos eliminar los branches y categorías de transifex para evitar confusión :dancer:

**Comment by a0viedo** [comment]
Perdón por llegar tarde pero +1 para es únicamente.

**Comment by ipeluffo** [comment]
Pregunta, ¿esto debería ser aceptado por los "owners" del repositorio original?
Porque en tal caso deberían modificar el repo [website](https://github.com/iojs/website/) y eliminar:
1. [es_AR](https://github.com/iojs/website/tree/master/content/es_AR)
2. [es_CO](https://github.com/iojs/website/tree/master/content/es_CO)
3. [es_ES](https://github.com/iojs/website/tree/master/content/es_ES)

Y mirar los cambios de [es_ES](https://github.com/iojs/website/tree/master/content/es_ES) a [es](https://github.com/iojs/website/tree/master/content/es)

**Comment by julianduque** [comment]
podemos crear un issue en [website](http://github.com/iojs/website) pidiendo eliminar esos directorios o enviar un PR

**Comment by edsadr** [comment]
+1 para el issue

**Comment by julianduque** [comment]
Ya envié el pull request a [website](http://github.com/iojs/website)

**Comment by julianduque** [comment]
Y ya le hicieron merge en menos de 3 minutos

![](https://i.cloudup.com/EWxu4w3hHm-3000x3000.png)

**Comment by vrunoa** [comment]
:+1:

**Comment by ipeluffo** [comment]
Perfecto! :+1:

**Comment by ipeluffo** [comment]
Dado este merge, ahora podemos borrar las localizaciones de Transifex ;)

**Comment by julianduque** [comment]
Yes!
