### ISSUE TITLE
Cómo colaborar

### ISSUE THREAD

**Issue by benoror** [iojs/iojs-es#51]
Hola!

Tal vez sea una pregunta estúpida, pero en mi caso es la primera vez que pretendo colaborar en un proyecto internacional, y quisiera saber si *hay alguna* **documentación oficial** *sobre convenciones y procedimientos para iniciar a colaborar?*. *O simplemente comienzo a* **enviar pull requests** *con mis correcciones a los archivos del repositorio?*

Disculpen la pregunta noob y de antemano gracias.

Saludos cordiales

**Comment by stringparser** [comment]
@benoror para nada hombre, la verdad es que llevamos dos semanas y todavía estamos un poco verdes :) y en cualquier caso, aunque fuera más vergüenza ninguna hombre :D. Para colaborar ahora mismo yo estoy usando la etiqueta [ayuda necesaria](https://github.com/iojs/iojs-es/labels/ayuda%20necesaria) y la milestone [pendiente](https://github.com/iojs/iojs-es/milestones/pendiente). 

PRs las que quieras.

**Comment by stringparser** [comment]
@benoror, hay un Hangout para la semana que viene, échale un vistazo al doodle que @julianduque ha dejado en #64

**Comment by ipeluffo** [comment]
Se esta trabajando para armar una guía sobre cómo colaborar en los distintos equipos.
Ver más información sobre los grupos en #83
