### ISSUE TITLE
Revisiones pendientes

### ISSUE THREAD

**Issue by stringparser** [iojs/iojs-es#53]
Un issue para ir dejando revisiones pendientes. Echar una mano ;)

* [Como io.js construyó un esfuerzo de traducción con 146 personas, 27 idiomas... en un día](https://github.com/iojs/iojs-es/blob/master/publications/medium-2015-02-como-iojs-construyo-localizacion-en-un-dia.md) 
  * Original: github: ¿?, medium [medium/@mikeal](https://medium.com/@mikeal/how-io-js-built-a-146-person-27-language-localization-effort-in-one-day-65e5b1c49a62)

* [Semana del 13 de Febrero](https://github.com/iojs/iojs-es/blob/master/publications/medium-2015-02-13-semana-del-13-de-Febrero.md) publicado en [https://medium.com/node-js-javascript](https://medium.com/node-js-javascript) 
   * Original:  github iojs/website#122, medium [medium/node-js-javascript](https://medium.com/node-js-javascript/io-js-week-of-february-13th-2015-7846b94074a2)

**Comment by vrunoa** [comment]
En el articulo [Como io.js construyó un esfuerzo de traducción con 146 personas, 27 idiomas... en un día](https://github.com/iojs/iojs-es/blob/master/publications/medium-2015-02-como-iojs-construyo-localizacion-en-un-dia.md) cambiaría la frase del *subtitulo*, ya que me parece que hace referencia a la pelicula ["Fields of dream"](http://en.wikipedia.org/wiki/Field_of_Dreams) por la siguiente:
*"Si le pides a una comunidad que lo construyan, ellos vendrán."*

**Comment by vrunoa** [comment]
Texto de mas en el articulo [Como io.js construyó un esfuerzo de traducción con 146 personas, 27 idiomas... en un día](https://github.com/iojs/iojs-es/blob/master/publications/medium-2015-02-como-iojs-construyo-localizacion-en-un-dia.md)
~~Lo que quería hacer en lugar de~~ "Parte de la visión de io.js es un proyecto que pueda crecer y florecer a través de una comunidad que contribuya y maneje cada parte del proyecto."

**Comment by vrunoa** [comment]
Dejo esto en el siguiente [PR](https://github.com/iojs/iojs-es/pull/56)

**Comment by julianduque** [comment]
Realicé un par de cambios de ortografía en transifex a esta publicación para que sea tenida en cuenta en el PR

**Comment by stringparser** [comment]
Ok @julianduque. ¿PR? o ¿cojo el texto de transifex?

**Comment by julianduque** [comment]
@stringparser con https://github.com/iojs/iojs-es/pull/58 es un +1 de mi parte

**Comment by ipeluffo** [comment]
Agregué algunos comentarios de correcciones en el PR... es una solución intermedia a usar Transifex y hacer PRs por cada modificación que a cada uno le parece :)

**Comment by stringparser** [comment]
Exacto, pero si hay gente a la que gusta más utilizar transifex bienvenido sea. Al fin y al cabo esto es tiempo libre de cada uno. Estuvimos discutiendo un poco de esto en #38 y la gente de iojs/iojs-it dio una idea bastante buena de cómo solucionar el tema de las PRs a iojs/website

**Comment by julianduque** [comment]
A mi transifex me gusta para la traducción inicial ya que ahí es directo al grano respecto a el esfuerzo colaborativo, cuando el artículo alcance un 100% se puede pasar al repo y en un PR se haría la revisión como la hemos hecho con las últimas dos publicaciones. Si alguien no se siente cómodo o no ha trabajado con GitHub con todo el gusto del mundo podemos hacer un hangout o tener un chat y juntos aprendemos :) 

Mi correo es julianduquej at gmail.com por si cualquier cosa y se que otros miembros del equipo estarán dispuestos a ayudar :dancer:

**Comment by stringparser** [comment]
#61 y #63 cierran este
