### ISSUE TITLE
Write Access

### ISSUE THREAD

**Issue by julianduque** [iojs/iojs-es#59]
¿Quiénes tienen write access al repo o cómo se gana uno ese hermoso privilegio?

Así se puede liberar la carga de algunos que estan administrando el repo ;)

**Comment by ipeluffo** [comment]
La otra alternativa sería que hagas merge de tu PR de manera autónoma, creo que @stringparser ha hecho eso

**Comment by edsadr** [comment]
@julianduque no estaba agregado al team por lo tanto no tenia write access... ahi acabo de agregarlo :)

**Comment by julianduque** [comment]
Yo sigo haciendo PR desde el fork para seguir el proceso correcto pero quería write access para ayudar a revisar otros PRs y liberar cargas :)

**Comment by julianduque** [comment]
Ya estoy en todo lado \o/ (eso me pasa por llegar tarde hehehe)

**Comment by stringparser** [comment]
hahahah
