### ISSUE TITLE
Publicación de: Como io.js construyó...

### ISSUE THREAD

**Issue by stringparser** [iojs/iojs-es#63]
@iojs/iojs-es 

Publicación de:
 [Como io.js construyó un esfuerzo de traducción con 146 personas, 27 idiomas... en un día](
  https://github.com/iojs/iojs-es/blob/master/publications/medium-2015-02-como-iojs-construyo-localizacion-en-un-dia.md
 )

En la publicación de la semana pasada (#61) se hace referencia en un link a este artículo y aún no está en medium.

**Comment by julianduque** [comment]
+1

**Comment by stringparser** [comment]
+1 y publicado, sólo por esta vez porque vamos con poco de retraso, https://medium.com/@iojs_es/como-io-js-construy%C3%B3-un-esfuerzo-de-traducci%C3%B3n-con-146-personas-27-idiomas-en-un-d%C3%ADa-dd1836be94ad

En cuanto estemos un poco más engrasados
