### ISSUE TITLE
Traductor / Colaborador

### ISSUE THREAD

**Issue by dosten** [iojs/iojs-es#65]
Hola a todos, mi nombre es Diego y soy de Buenos Aires, Argentina. Developer hace 8 años. Me gustaría colaborar con el proyecto.

Saludos!

**Comment by ipeluffo** [comment]
@dosten , bienvenido y gracias por el apoyo.
Aún estamos mejorando la metodología para colaborar en el proyecto.

Por ahora, estamos usando un servicio llamado Transifex para hacer las primeras traducciones de los documentos.
Te recomiendo registrarte en el repositorio de iojs-es en Transifex.

Saludos!

**Comment by julianduque** [comment]
Bienvenido @dosten !

**Comment by dosten** [comment]
@ipeluffo @julianduque muchas gracias! ahora me registro en el repo de Transifex!

**Comment by dosten** [comment]
Ya me registre, espero aprobación en los teams de Español y Español (Argentina).

**Comment by edsadr** [comment]
@dosten aprobado ... pero acabo de eliminar Español (Argentina) ... el equipo voto y decidió solo mantener español neutro
