### ISSUE TITLE
Colaborador

### ISSUE THREAD

**Issue by buritica** [iojs/iojs-es#67]
Hola, yo he organizado una serie de eventos y meetups de JS en Latinoamerica y me gustaría echarles una mano aca.

**Comment by ipeluffo** [comment]
@buritica , bienvenido y gracias por el apoyo.
Aún estamos mejorando la metodología para colaborar en el proyecto.

Por ahora, estamos usando un servicio llamado Transifex para hacer las primeras traducciones de los documentos.
Te recomiendo registrarte [en el repositorio de iojs-es en Transifex](https://www.transifex.com/projects/p/iojs-es/).

Saludos!

**Comment by julianduque** [comment]
Bienvenido mi querido @buritica !!! Que bueno trabajar con vos :dancers:

**Comment by stringparser** [comment]
Bienvenido!! :)

**Comment by a0viedo** [comment]
@buritica bienvenido!

**Comment by eafelix** [comment]
Bienvenido @buritica !

**Comment by stringparser** [comment]
Cerramos este @buritica, si te apetece pasate por #41 ;)
