### ISSUE TITLE
Colaborador

### ISSUE THREAD

**Issue by icnovaro** [iojs/iojs-es#69]
Buen día, 

Hoy José Alvarez, colaborador de este proyecto me comentó de la idea que tienen y pues yo ni corto ni perezoso le pregunté que ¿Cómo podría colaborar? y heme aquí dispuesto a ayudar en lo que necesiten (traductor).

Soy desarrollador de software, apasionado por esto que para mí es "un estilo de vida".

**Comment by julianduque** [comment]
Hola José! Bienvenido! Aquí puedes hacer revisiones de contenidos, estate muy pendiente de los issues y tenemos unc hat donde nos comunicamos acá: https://gitter.im/iojs/iojs-es

**Comment by icnovaro** [comment]
Jejejejeje Soy Iván Casanova, mi amigo el cual también es colaborador se llama José. Estaré pendiente para colaborar.

**Comment by julianduque** [comment]
@icnovaro hahaha que pena Iván, ya corregí el comentario :sweat_smile:

**Comment by soybackend** [comment]
@julianduque :D me traje uno de los mejores que hay en la ciudad. Se que va a ayudar mucho!

**Comment by julianduque** [comment]
@soybackend yes!!

**Comment by stringparser** [comment]
Bienvenido @icnovaro! :)

**Comment by a0viedo** [comment]
@icnovaro bienvenido!

**Comment by stringparser** [comment]
Cerramos este también, si te aburres pasa por #41 y cuentanos cosicas :D

**Comment by stringparser** [comment]
Y por cierto, no eras colaborador todavía @icnovaro... ahora si! :)
