### ISSUE TITLE
Publicación Febrero 20

### ISSUE THREAD

**Issue by julianduque** [iojs/iojs-es#70]
Original - https://medium.com/node-js-javascript/io-js-week-of-february-20th-2015-48486615980

Ya está listo para empezar a traducir

**Comment by ipeluffo** [comment]
¿Alguien sabe de donde conseguir el markdown del artículo así lo subimos a Transifex?

**Comment by julianduque** [comment]
Aquí https://github.com/iojs/website/issues/188#issuecomment-75297323

**Comment by ipeluffo** [comment]
:+1:

**Comment by stringparser** [comment]
+1

**Comment by ipeluffo** [comment]
Ya tengo una primera versión de la traducción, si quieren hago un PR

**Comment by stringparser** [comment]
Of course ;)

**Comment by ipeluffo** [comment]
Done... Ver #71

**Comment by ipeluffo** [comment]
¿Alguien quedó a cargo de publicar el último artículo en Medium?
No tengo las claves de acceso para hacerlo, una vez hecho podemos cerrar este issue.

**Comment by stringparser** [comment]
¿No las tienes? Te las acabo de enviar por correo ;) y así puedes publicar tu #71

**Comment by ipeluffo** [comment]
Gracias @stringparser !

**Comment by stringparser** [comment]
¡Que menos! :)

**Comment by ipeluffo** [comment]
Ya quedó publicado el [artículo](https://medium.com/@iojs_es/io-js-semana-del-20-de-febrero-de-2015-c7a4c57bafb5)... cierro el issue :+1:
