### ISSUE TITLE
Traducir comentarios de website

### ISSUE THREAD

**Issue by julianduque** [iojs/iojs-es#72]
Relacionado: https://github.com/iojs/website/issues/225

**Comment by sergiolepore** [comment]
Este comentario lo pasamos directamente a los `.md` en transifex?

**Comment by julianduque** [comment]
@sergiolepore todavía no, creo que se requiere hacer desde el build step del website y no es tan visible, asi que esto podria esperar

**Comment by ipeluffo** [comment]
¿Cerramos este issue? ¿Se asigna a alguien de Website?

**Comment by stringparser** [comment]
Me asigno
