### ISSUE TITLE
Mejorando el flujo de trabajo con transifex

### ISSUE THREAD

**Issue by edsadr** [iojs/iojs-es#74]
Explorar la opción de implementar: http://docs.transifex.com/developer/integrations/github

Lo cual haria commit y push directamente al repositorio desde transifex, hay que probarlo pero si funciona entonces resuleve el problema de sync

**Comment by SametSisartenep** [comment]
@edsadr +1
Voy a echarle un vistazo. Avisadme si necesitáis ayuda para hacer testing y demás ;)

**Comment by julianduque** [comment]
+1

**Comment by stringparser** [comment]
+10E+6 :)

**Comment by sergiolepore** [comment]
Relacionado a #64

**Comment by italoacasas** [comment]
+1

**Comment by stringparser** [comment]
¿Alguna cosa nueva por aquí?

**Comment by edsadr** [comment]
Hasta donde lo deje habia que ponerlo a funcionar en una maquina... pero como estoy descatualizado la pregunta es... no veo movimiento en transifex... dejaron de usarlo? si es así se cierra este issue

**Comment by stringparser** [comment]
Yo deje de usarlo al ver falta de human resources :smile:, ya sabes que prefiero git. Acabo de mirar en transifex y veo que el último artículo subido es el del 13 de Febrero... así que si, no hay nadie que haya puesto materia allí.

**Comment by edsadr** [comment]
Cerrando esto entonces =)
