### ISSUE TITLE
Reemplazar asincrono en el contenido actual

### ISSUE THREAD

**Issue by edsadr** [iojs/iojs-es#76]
Ya que agregamos las palabra *asynchronous* y *synchronous*  al glosario aquí: https://github.com/iojs/iojs-es/pull/75 .. hay que reemplazarlas en el contenido actual

**Comment by stringparser** [comment]
Sep, ¿aparecen por algún lado por ahora?

**Comment by stringparser** [comment]
Ok, vale que me estoy poniendo al día. Me asigno ;)

**Comment by ipeluffo** [comment]
¿La idea sería reemplazar cualquier uso de los términos?
Pregunto porque *asincrónico / asíncrono*) y *sincrónico / síncrono* son términos comúnmente utilizados en literatura en Español.

**Comment by a0viedo** [comment]
Yo elegiría alguno de los dos (*asincrónico / asíncrono*) e intentaría ser consistentes en todos los textos.

**Comment by stringparser** [comment]
Si, ¿os parece bien síncrono? me suena más cercano al verbo sincronizar y hay muchos nombres que vienen de verbos (viaje, viajar; sabor, saborear; programa, programar; etc.). 

Y asíncrono esta en la rae http://lema.rae.es/drae/?val=s%C3%ADncrono :) aunque síncrono nop :( hahaha

**Comment by ipeluffo** [comment]
¿Cerramos o asignamos a los distintos grupos?

**Comment by stringparser** [comment]
Esto cae dentro de documentación y yo estoy asignado, pero si, pasémoslo a el grupo de trabajo de documentación.

**Comment by stringparser** [comment]
Hahah, pensándolo bien es revisión. ¿Te asignas?

**Comment by stringparser** [comment]
He hecho un grep y parece que va todo bien, cierro este
