### ISSUE TITLE
Traducción API - Sección "C/C++ Addons"

### ISSUE THREAD

**Issue by SametSisartenep** [iojs/iojs-es#78]
He creado esta issue en base a la propuesta de @ipeluffo en https://github.com/iojs/iojs-es/issues/73#issuecomment-75841808 .
Me gusta la idea de crear una issue enfocada a cada sección específica ...muy UNIX :P

**Comment by ipeluffo** [comment]
:+1: , te lo asigno :)

**Comment by ipeluffo** [comment]
Ahora si :+1:

**Comment by SametSisartenep** [comment]
@ipeluffo Le he dado a "**asign yourself**" ;)

**Comment by SametSisartenep** [comment]
Genial, gracias :)

**Comment by SametSisartenep** [comment]
Acabo de forkear el repo de @rvagg `node-addon-examples` bajo el nombre `ejemplos-addon-node`.

¿Cómo me recomendáis estructurarlo? Es decir, ¿Hago cambios sobre los archivos y mantengo el repo como referencia, o creo una carpeta aparte que se llame "**es_ES**" o algo similar y ahí creo un clon del repo, modifico los archivos y hago PR a espera de @rvagg?

Toda sugerencia es bienvenida :)

**Comment by SametSisartenep** [comment]
el repo lo podéis encontrar [aquí](https://github.com/SametSisartenep/ejemplos-addon-node), aunque pienso que sería mejor crearlo en la organización **iojs-es** en caso de hacerlo en base a la primera opción.

**Comment by SametSisartenep** [comment]
También estoy viendo que los ejemplos de código que muestran en la documentación no son los mismos que hay en el repositorio. Voy a compilar algunos para ver cuál es la sintaxis correcta.

**io.js API 1.3.0**
```cpp
// hello.cc
#include <node.h>

using namespace v8;

void Method(const FunctionCallbackInfo<Value>& args) {
  Isolate* isolate = Isolate::GetCurrent();
  HandleScope scope(isolate);
  args.GetReturnValue().Set(String::NewFromUtf8(isolate, "world"));
}

void init(Handle<Object> exports) {
  NODE_SET_METHOD(exports, "hello", Method);
}

NODE_MODULE(addon, init)
```

**Ejemplos de _rvagg_**
```cpp
#include <node.h>
#include <v8.h>

using namespace v8;

Handle<Value> Method(const Arguments& args) {
  HandleScope scope;
  return scope.Close(String::New("world"));
}

void init(Handle<Object> exports) {
  exports->Set(String::NewSymbol("hello"),
      FunctionTemplate::New(Method)->GetFunction());
}

NODE_MODULE(hello, init)
```

**Comment by SametSisartenep** [comment]
Ya lo he probado y ambas formas funcionan. No cambiaré la metodología.

**Comment by stringparser** [comment]
que crack :)

**Comment by stringparser** [comment]
Cerramos este ya que #93 está en el repo
