### ISSUE TITLE
Propuesta de reconciliación con joyent/node

### ISSUE THREAD

**Issue by edsadr** [iojs/iojs-es#80]
Bueno chicos según este issue: https://github.com/iojs/io.js/issues/978 tenemos que votar a ver si estamos de acuerdo con ello o no..

**Comment by academo** [comment]
En tanto siga siendo open governance +1

**Comment by a0viedo** [comment]
Hubo ciertas razones por las cuales se llegaron a la situación en la que estamos. Hoy, esas razones siguen siendo parte de la ecuación (Board de Joyent) en cuanto a la Fundación. Joyent quiere atraer usuarios y contribuyentes a su proyecto, pero ni siquiera tiene un [Code of Conduct](https://github.com/joyent/node/blob/master/CONDUCT.md) por ejemplo. Por otro lado, yo creo que hay cierta gente (i.e. TJ Fontaine) participando cómo contribuidores en [joyent/node](https://github.com/joyent/node) sólo porque es su trabajo, y no porque les interesa lo mejor para el proyecto (aún si lo mejor sería desentenderse de Joyent). 

Mi voto es no positivo :-1:

**Comment by fcanela** [comment]
Supongo que solamente puden votar colaboradores del proyecto, ¿no es así?

**Comment by ipeluffo** [comment]
Creo que no estoy al tanto de todos los detalles para dar un voto sobre esta decisión tan relevante para el/los proyecto/s.

Por otro lado, adhiero con @academo que de seguir una política *open governance* y si la unión de la fuerza de ambos proyectos es para el bien de node.js/io.js estoy de acuerdo que haya una reconciliación.

@a0viedo , estuve mirando el issue original y vi lo siguiente (los links son incorrectos):
> As an initial agreed upon structure, beyond what is in the bylaws, the following documents would be adopted from io.js.
>
> GOVERNANCE.md (TC, Voting, etc.)
> CONTRIBUTING.md (Collaborator policy, CoC, DCO, etc.)
> WORKING_GROUPS.md
> ROADMAP.md
> In addition to the definition of "collaborator" from CONTRIBUTING.md the list of existing collaborators to io.js would also transfer.

De esta manera estarían solucionando la carencia de un *Code of Conduct*.

Saludos y que sea lo mejor para los proyectos

**Comment by eafelix** [comment]
open governance +1

**Comment by a0viedo** [comment]
@ipeluffo pero mi punto es, joyent/node obtendría un CoC (tanto como el CONTRIBUTING.md, ROADMAP.md, etc) sólo por el merge. es decir, pareceria que alguien se los tiene que exigir/demandar para que lo adopten. el hecho de que hayan sido creados naturalmente en io.js es la gran diferencia

**Comment by krosti** [comment]
Una ventaja y beneficio de io.js es que no depende de que mañana se levante joyent con el pie izquierdo y tome la desicion que quiera.  Estaria bueno que las licencias nos apoyen aqui. De todas formas me parece absurdo,  por otro lado,  que haya dos forks de 'casi lo mismo' buscando ganarse la aceptacion porque haria a mi entender una sectorizacion demasiado granular quizas y se perderian muchas cosas del sistema de colaboracion para ambos sentidos.  Proyectos no compatibles pero utiles de joyent/node que no anduviesen en io.js o viceversa seria super absurdo.  En conclusion: Me gustaria que se mergee pero con un open governance bien claro como el actual.

**Comment by SametSisartenep** [comment]
Creo que deberíamos esperar un poco, para ver cómo avanza el tema de la Fundación:
> As @mikeal said, the move to establish a Foundation was announced with Fidelity, IBM, Joyent, Microsoft, Paypal and SAP as the first members. But that was just to start - I am very confident there will be more joining before the Foundation launches later this year.

Y por parte de los contribuidores y usuarios (que han participado en la discusión), parece haber principal interés por mantener el modelo de gobierno abierto, actualizaciones continuas de cada una de las bibliotecas (i.e libuv, V8...) y soporte a largo plazo para determinadas versiones (ésta última más reclamada por parte de las compañías https://github.com/iojs/io.js/issues/978#issuecomment-76448180).

**Comment by julianduque** [comment]
Mi voto es un +0, veo dificil que Joyent acepte pero la discusión alrededor es positiva y cada vez se va mostrando las verdaderas intenciones de todas las partes.

Con la fuerza que ha tomado `io.js` podría vivir solo sin `Node`

**Comment by SametSisartenep** [comment]
@julianduque :metal: :+1:

**Comment by italoacasas** [comment]
-1

Ya e dicho el porque 10 veces en el gitter

**Comment by mikeal** [comment]
I have no idea what is being said exactly but if you have any followup questions for me I'm more than happy to answer.

**Comment by julianduque** [comment]
@mikeal thanks, we will let you know, from this thread we are agree about the reconcilitation proposal if new `Node` will continue working as `io.js` is working right now, and if the reconcilitation never happens we will still be so happy contributing to `io.js` as is :)

**Comment by mikeal** [comment]
@julianduque cool, the proposal has the new `Node` using the same governance policy and working group structure as `io.js` :)

**Comment by 007lva** [comment]
+1 Solo si la fundación usa el mismo modelo que iojs

**Comment by stringparser** [comment]
+1 if no fundation and open governance

**Comment by stringparser** [comment]
Cerrando en favor de #123
