### ISSUE TITLE
Publicación Febrero 27

### ISSUE THREAD

**Issue by julianduque** [iojs/iojs-es#81]
Ya se publicó: https://medium.com/node-js-javascript/io-js-week-of-february-17th-9422a589302a

[Estoy preguntando por el markdown](https://github.com/iojs/evangelism/issues/4#issuecomment-76530540) para que sea mas fácil traducirlo

**Comment by vrunoa** [comment]
Ahi respondieron, que van a estar los markdown en la carpeta [./weekly-updates](https://github.com/iojs/evangelism/tree/master/weekly-updates). Deberíamos crear la misma carpeta en el repo de iojs-es ? O estos irian en la carpeta ```publications``` ?

**Comment by julianduque** [comment]
@vrunoa con tal que tengamos una carpeta con el contenido el nombre es lo de menos, podemos renombrar publications to weekly-updates para estar sincronizados con el proyecto si eso nos hace a nosotros la tarea mas fácil :)

**Comment by vrunoa** [comment]
buenisimo @julianduque . mejor si mantenemos todo con el mismo nombre, mas fácil de referenciar entre repositorios. :+1:

**Comment by SametSisartenep** [comment]
@vrunoa @julianduque :+1:

**Comment by stringparser** [comment]
¿Cómo va esto? Yo tengo un rato hoy por la tarde y si no lo traduzco. Aunque no es tan largo, ¿podríais echarle un vistazo alguno y hacerlo? Lo digo porque yo estoy en los grupos de trabajo del website y documentación pero no en evangelización.

**Comment by stringparser** [comment]
@iojs/iojs-es Traduciendo. Quien esté en ello que hable ahora :)

**Comment by stringparser** [comment]
Ok, traducido en https://github.com/iojs-es/evangelism/pull/1
