### ISSUE TITLE
iojs-es Reunion del Grupo de Trabajo, 3 de Marzo

### ISSUE THREAD

**Issue by italoacasas** [iojs/iojs-es#84]
Hola a todos, como e pasado por varios meeting y conozco el caos improductivo que se puede volver, estoy tratando de organizar toda la información para guiarnos, si nadie pone un -1 me gustaría guiar el meeting es decir, hacer las preguntas, y darle la palabra a cada uno. Para que exista un orden y poder escuchar las opiniones de todos. Luego que todos los que quieran hablan de un tema lo hagan, votamos y así se tomaran las decisiones. 

## Agenda de la Reunion

- Grupos de Trabajo #83 
  - Comentar sobre lo que dice @julianduque en #84 (limitar a 2 los grupos de trabajo que una persona      puede estar)
- Workflow del Proyecto (Pull request a iojs, etc) #38 
- Workflow de Traducción de la Documentación #73 #74 
- Actualización del Website #82
- Como trabajar con las publicaciones semanales #81 
- Redes Sociales
- Canal de IRC donde se pueda crear una comunidad en nuestro idioma
- Tareas administrativas
  - Limitar cantidad de labels verde/naranjas que pueden existir en un issue al mismo tiempo
- Propuesta de reconciliación con Joyent/Node #80 

----En desarrollo----

**Comment by a0viedo** [comment]
Genial @italoacasas. Habría que escribir una minuta (resúmen) del hangout también, te lo encargamos a vos?

Pienso que podríamos agregar:

> Como trabajar con las publicaciones semanales #81

Quisiera que se charle del workflow en general y bajarlo a un documento. Issues relacionados:
- https://github.com/iojs/iojs-es/issues/38
- https://github.com/iojs/iojs-es/issues/74

-------------
Asegurarse de que todos opinaron en https://github.com/iojs/iojs-es/issues/80

-------------
Podría discutirse incorporar un límite a la cantidad de labels verdes/naranjas que pueden existir al mismo tiempo?

**Comment by stringparser** [comment]
@iojs/iojs-es añadir lo que os parezca antes de mañana ;)

Relacionados: #83, #82, #3, iojs/website#246, #73

**Comment by ipeluffo** [comment]
Creo que los puntos:
* Workflow del Proyecto (Pull request a iojs, etc) #38
* Workflow de Traducción de la Documentación #73 #74

Se pueden tratar juntos ya que el Workflow debería ser parecido sino igual.

Si fuera necesario, en "Tareas administrativas" agregaría un sub-item con lo comentado por @a0viedo sobre el límite de cantidad de labels (para no olvidar el tema solamente).

El resto +1 :+1:

**Comment by italoacasas** [comment]
@ipeluffo yo solo estoy organizando se hace como mas facil nos sea hablarlo luego, lo separe porque el del proyecto seria como trabajar con iojs(PR) y el de la documentación seria como vamos a trabajar nosotros con las traducción(Transifex).

Espero porque alguien mas comente sobre este punto

**Comment by a0viedo** [comment]
les dejo mi opinión acerca del workflow y cómo debería ser para cualquier texto:

- se sube el texto original a transifex
- se traduce desde transifex
- se realiza una revisión (idealmente por otra persona que no haya realizado la parte de traducción)
- con la traducción finalizada, se commitea a la org [iojs-es](https://community.workday.com/rest). desde ahí  se hace el PR a [iojs/iojs-es](https://github.com/iojs/iojs-es)

---------
Otra cosa que quisiera que se charle es la necesidad de saber en qué está cada uno. Esto es importante porque cada vez se suman nuevos colaboradores y sirve para que no estén dos personas traduciendo lo mismo. Por ejemplo, eso se estuvo organizando con la documentación en https://github.com/iojs/iojs-es/issues/73.

**Comment by stringparser** [comment]
+1, aunque, en mi caso yo añadiría también el texto en github y combiar las correciones hechas en transfifex con las que se hagan a un PR de aquí.

He estado mirando, y en github no se puede hacer una PR a menos que sea un fork directo. Digo esto porque estaba explorando la posibilidad de mantener los repositorios que hay que localizar como branchs en este repo. Es decir tener iojs/iojs-es:website, iojs/iojs-es:roadmap, etc. Pero como digo, no es posible porque aunque hagas una branch con la intención de: limpiar su historia y luego merge con un el upstream de interés (digamos iojs/website) con la idea de luego poder hacer PRs desde ahí a iojs/website no es posible.

Y la opción de mantenerlo todo en la Org. iojs-es es lo más simple. Se podrían hacer todas las PRs inciales igualmente aquí, pero la final habría que hacerla desde un repo de la Org. iojs-es que sea un fork del de iojs. 

Si se consiguiera hacer una integración trasifex-github como se habló en #74 sería perfecto.

**Comment by ipeluffo** [comment]
Me parece correcto el workflow. Incluso creo que es la versión en limpio de lo que se discutió en los issues.

Como dice @stringparser , los forks de todos los repos de iojs se harían en la org [iojs-es](https://github.com/iojs-es) y desde allí se harían los PR.

Es decir, si uno quiere colaborar debería hacer fork del repo de [iojs-es](https://github.com/iojs-es), luego hacer el PR allí, y finalmente se hace un PR a [iojs](https://github.com/iojs).
¿Habría que agregar a los colaboradores a la org iojs-es?
Espero no haberme confundido, sino me corrigen :)

La integración de Transifex con Github sería muy bueno, por mi lado no tuve tiempo de investigar sobre el tema.

**Comment by stringparser** [comment]
No necesariamente @ipeluffo. Esto hay que hablarlo, por supuesto, pero lo óptimo sería que sólo hacer un fork de este repositorio. Tener aqui una branch sincronizada con el repositorio de iojs que corresponda. Y luego hacer un merge con el repo de la org iojs-es. Esto conserva el nombre del colaborador, historia, etc. y sería automatizable. Pero insisto, hay que hablarlo. :)

**Comment by julianduque** [comment]
Tuvimos algunos inconvenientes logisticos en la reunión pero en resumen:

* Debemos trabajar como Equipos de Trabajos y reunirnos para definir el flujo de trabajo, este sería diferente para cada grupo de trabajo
* Se creó una organización https://github.com/iojs-es donde vamos a mantener los repos originales sincronizados para facilitar procesos de traducción y PR
* La idea de los miembros de los grupos de trabajo es involucrar a los nuevos colaboradores para que trabajen en los grupos y poder delegar tareas (divide y venceras)
* Se debe escribir una guía de contribución para que cada nuevo colaborador sepa como puede trabajar, que tareas hay pendientes, que lideres de los grupos de trabajo hay disponibles para pedirles ayuda, consejo, etc
* Este repositorio seria el centro de las tareas y comunicación, debemos ser efectivos en la escritura y mantenimiento de los issues

No se si se me pasa algo @stringparser @ipeluffo @edsadr @italoacasas que estuvieron en la reunión por favor agregar sus notas :)

**Comment by italoacasas** [comment]
- Guías: Tal vez podamos hacer una guía general y luego los lideres de cada grupo pueden crear una especifica e ir actualizándola, para esto primero que habría que difinir lideres de grupos. feedback please

**Comment by sergiolepore** [comment]
Hola! Perdón por no haber estado ayer. Quién hosteó el Hangout al final? Hay video en algún lado?

**Comment by eafelix** [comment]
igualmente, perdón, pero con mucho trabajo. Muy buena la minuta de la reunion.
Me gusta la idea de la guia y la forma de organizarlo así no estamos con telefono descompuesto o desaliñados.

**Comment by julianduque** [comment]
@sergiolepore no hubo video pues tuvimos problemas técnicos y terminamos en un hangout normal

**Comment by ipeluffo** [comment]
@julianduque , muy buena minuta de la reunión. No tengo nada para agregar.

**Comment by stringparser** [comment]
@julianduque yo tampoco, y perdonad el retraso en contestar. ¿Abrimos un issue para cada grupo de trabajo y así podemos ir distribuyendo? Respecto a dividir el trabajo @ipeluffo hizo el comentario en el hangout de delegar el trabajo respectivo a cada Grupo de trabajo, incluida la descentralización de este repo. Si no recuerdo mal, esto implicaría:
 1. Hacer todos los cambios en cada repo de la org iojs-es.
 2. Tener este repositorio para el material común (glosario, etc.) y punto de partida para colaboradores y traductores

Voy a  abrir un issue de cada grupo de trabajo y si os parece bien, vamos elaborando un documento de colaboración entre todos.

**Comment by stringparser** [comment]
Listo :racehorse:

**Comment by stringparser** [comment]
Cerramos este ya que esta todo en marcha
