### ISSUE TITLE
Colaborador

### ISSUE THREAD

**Issue by carloscarcamo** [iojs/iojs-es#85]
Saludos a tod@s, primeramente felicitarles por el excelente trabajo que estan haciendo con la traducción de [io.js](https://iojs.org/en/index.html). Como parte del mundo de habla hispana aprecio mucho sus efuerzos.

Me presento ante la comunidad, mi nombre es Carlos Cárcamo, me dedico a la programación web, me gustan muchos lenguajes de programación y js es uno de mis preferidos desde que lo puedo usar en el back-end, he trabajado un poco con Node.js con algo de robotica y otras cosas, me gusta mucho y me di cuenta recientemente que existe este fork io.js. Noto que el desarrollo de io.js es bastante acelerado comparado con node.js y sin dudas es un proyecto interesante.

Llendo al grano, pongo a dispocición algo de mi tiempo para colaborar con la traducción de io.js. si ustedes lo necesitan, sera un pacer porder ayudar :)

**Comment by a0viedo** [comment]
Bienvenido @carloscarcamo! Te dejo dos links relacionados: https://github.com/iojs/iojs-es/issues/51 y https://github.com/iojs/iojs-es/issues/3. Cualquier pregunta que tengas, hacenosla saber.

**Comment by stringparser** [comment]
Bienvenido! :D

**Comment by stringparser** [comment]
Te añadí como colaborador, pasa por #41 si quieres a dejar lo que tienes aquí escrito ;)
