### ISSUE TITLE
Colaborador

### ISSUE THREAD

**Issue by GolloDev** [iojs/iojs-es#86]
Hey, podría colaborar en algo! :)

**Comment by stringparser** [comment]
Muy buenas @GolloDev! Pues claro hombre, ¿qué te apetece más traducir o colaborar en general?

**Comment by GolloDev** [comment]
pues traducir podría ser...

**Comment by stringparser** [comment]
Ok, pues ahora mismo creo que queda por traducir el último artículo de medium (#81) y si no en cualquier sección de la API (#73). Pronto será más sencillo buscar cosas que hacer. De hecho, si tienes tiempo, hoy hay un Hangout #64 y si quieres puedes pasarte. 

En cualquier caso te añado a los colaboradores y así puedes empezar.

**Comment by GolloDev** [comment]
la tarea es traducir la documentacion de la API? no?

**Comment by stringparser** [comment]
Hey @GolloDev, sip o el artículo de medium :)

**Comment by GolloDev** [comment]
Ok, puedo elegir que una sección de la API? agregame cuando puedas y voy colaborando entonces :)

**Comment by stringparser** [comment]
Si, la sección que quieras. Y debes de estar agregado, ve aquí si no y me dices si ves la invitación

**Comment by GolloDev** [comment]
si listo, gracias :)

**Comment by ipeluffo** [comment]
Bienvenido @GolloDev , te invito a ver el issue #83 sobre los Grupos de Trabajo.
Elegir en cual quieres participar y luego visitar el issue del grupo ( #94 , #95 , #96 , #97 ) para consultar en qué podes colaborar.

Saludos!

**Comment by GolloDev** [comment]
Ok gracias! :)

**Comment by a0viedo** [comment]
@gollodev bienvenido! podés pasar por https://github.com/iojs/iojs-es/issues/41 si querés a presentarte
