### ISSUE TITLE
Easter eggs everywhere

### ISSUE THREAD

**Issue by stringparser** [iojs/iojs-es#91]
Una cosa más, hay un `easter egg` en cada página (ver iojs/website#225 y iojs/website#258)

> Lets you localize the following however you like (a joke, url to your local group, both projects, etc.)

Básicamente nos dicen que podemos hacer alguna broma o que nos parezca. 
Ver https://github.com/iojs/website/pull/258#issuecomment-76962406

**Comment by edsadr** [comment]
+1

**Comment by stringparser** [comment]
iojs-es/website: @stringparser, @vrunoa, @GolloDev  
Un voto más para traducirlo o poner algo gracioso y hacemos un PR con una propuesta en iojs-es/website antes de hacerlo en iojs/website

**Comment by vrunoa** [comment]
:+1:

**Comment by stringparser** [comment]
Ok, tengo que ir a hacer unas cosas y cuando vuelva hago un PR con esto en el iojs/website (o si quiere alguno hacerla antes mejol :))

**Comment by stringparser** [comment]
Aquí esta: iojs-es/website/pull/2
